.PHONY: all

run-validator:
	./scripts/run-validator.sh

run-relayer:
	./scripts/run-relayer.sh
	
run-deploy:
	chmod +x ./scripts/deploy-contract.sh
	./scripts/deploy-contract.sh

run-deploy-warp:
	chmod +x ./scripts/deploy-warp.sh
	./scripts/deploy-warp.sh

run-send-message:
	chmod +x ./scripts/send-msg.sh
	./scripts/send-msg.sh

run-send-transfer:
	chmod +x ./scripts/send-transfer.sh
	./scripts/send-transfer.sh