blasttestnet:
  name: blasttestnet
  chainId: 168587773
  domainId: 168587773
  protocol: ethereum
  rpcUrls:
    - http: https://sepolia.blast.io
  nativeToken:
    name: Ether
    symbol: ETH
    decimals: 18