# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: sepolia
    standard: EvmHypCollateral
    name: Sipher Token
    symbol: SIPHER
    decimals: 18
    addressOrDenom: "0x21b044ceE37B6bd05b923D9f02394C294aE66964"
    collateralAddressOrDenom: "0x7f0c2f38d6386268f49501707dd1421fd03353fc"
    connections:
      - token: ethereum|zircuittestnet|0xa9c12F47836207879Ec1bbec09361DB932Db2f09
  - chainName: zircuittestnet
    standard: EvmHypSynthetic
    name: Sipher Token
    symbol: SIPHER
    decimals: 18
    addressOrDenom: "0xa9c12F47836207879Ec1bbec09361DB932Db2f09"
    connections:
      - token: ethereum|sepolia|0x21b044ceE37B6bd05b923D9f02394C294aE66964
