# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: sepolia
    standard: EvmHypNative
    name: Ether
    symbol: ETH
    decimals: 18
    addressOrDenom: "0x0a8bF6AF06Bc301a9C8548382Fa91daf49099dd9"
    connections:
      - token: ethereum|zircuittestnet|0x24B8018c87f3e2b8bD7F8F0726b59F2d94B857AA
  - chainName: zircuittestnet
    standard: EvmHypSynthetic
    name: Ether
    symbol: ETH
    decimals: 18
    addressOrDenom: "0x24B8018c87f3e2b8bD7F8F0726b59F2d94B857AA"
    connections:
      - token: ethereum|sepolia|0x0a8bF6AF06Bc301a9C8548382Fa91daf49099dd9
