# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: sepolia
    standard: EvmHypNative
    name: Ether
    symbol: ETH
    decimals: 18
    addressOrDenom: "0xF3EF9E3aF0f4696D9DBcC26140F7c0a52188BDf0"
    connections:
      - token: ethereum|zircuittestnet|0x1A145b7761e2B7D939eaABeAA2b8ef5aAeb813fD
  - chainName: zircuittestnet
    standard: EvmHypSynthetic
    name: Ether
    symbol: ETH
    decimals: 18
    addressOrDenom: "0x1A145b7761e2B7D939eaABeAA2b8ef5aAeb813fD"
    connections:
      - token: ethereum|sepolia|0xF3EF9E3aF0f4696D9DBcC26140F7c0a52188BDf0
