hyprtestnet:
  name: hyprtestnet
  chainId: 882
  domainId: 882
  protocol: ethereum
  rpcUrls:
    - http: https://rpc-testnet.hypr.network/
  nativeToken:
    name: Ether
    symbol: ETH
    decimals: 18